### ISSUE TITLE
Got things working with Angular-cli

### ISSUE THREAD

**Issue by nigel-dewar** [Breeze/temphire.angular#10]
@marcelgood hey mate, just thought id give heads up that got things working fine with angular-cli in the end

Here is what I needed to do, if you wanted a head start on a couple of things.

Add the goodies required to package.json - Also not the mod I make on the "Start" so to use a proxy for angular-cli

{
  "name": "angular-breeze-test",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --proxy-config proxy.config.json",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "breeze-bridge-angular": "^4.0.0-alpha1",
    "breeze-client": "^1.6.3",
    "lodash-es": "^4.17.4",
    "bootstrap": "^3.3.7",
    "jquery": "^3.2.1",
    "font-awesome": "^4.7.0"
  },
  "devDependencies": {
    "@types/jquery": "^2.0.41",
    "@types/lodash": "^4.14.58",
    "@types/lodash-es": "^4.14.5",
  }
}
_________________________________________________

Install jquery in angular-cli using this as guide 
https://www.gurustop.net/blog/2016/11/18/3821/jquery-angular2-angularcli-how-to
this important part is doing this
npm install @types/jquery --save-dev

So that '$' is recognized throughout the ts files
___________________________________________
In  tsconfig.app.json, add "jquery"
"types": [
      "jquery"
    ]
___________________________________________
In .angular-cli.json, add

"styles": [
        "styles.css",
        "../node_modules/bootstrap/dist/css/bootstrap.css",
        "../node_modules/font-awesome/css/font-awesome.min.css"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.min.js",
        "../node_modules/bootstrap/dist/js/bootstrap.min.js"
      ],
_____________________________________________________
You will need to run angular-cli proxy whilst in dev to ensure calls to breeze webapi works
this video shows how and explains why https://juristr.com/blog/2016/11/configure-proxy-api-angular-cli/

Create a file in the root on your angular-cli project called proxy.config.json
Put this in it
{
  "http://localhost:49795/breeze/*":{
    "target": "http://localhost:49795",
    "secure": false,
    "logLevel": "debug"
  }
}

____________________________________________________

Then all should be good to go, just setup CORS in webapi of course. Hope it works for you.

**Comment by marcelgood** [comment]
Thanks

**Comment by nigel-dewar** [comment]
No worries mate. Close this if ur cool with it. Cheers.
