### ISSUE TITLE
override parseDateFromServer 

### ISSUE THREAD

**Issue by fayeeg** [Breeze/temphire.angular#12]
With reference to the issue discussed in this URL,
https://stackoverflow.com/questions/17657459/breezejs-date-is-not-set-to-the-right-time

where should I put this piece of code in the temphire angular solution?

breeze.DataType.parseDateFromServer = function (source) {
     var date = moment(source); 
     return date.toDate();   
};

**Comment by marcelgood** [comment]
This would best be placed in the EntityManagerProvider along with all the other Breeze configuration.

https://github.com/Breeze/temphire.angular/blob/master/TempHire/app/core/services/entity-manager-provider.ts#L31

**Comment by fayeeg** [comment]
Thanks marcelgood.

if anyone has similar requirements, I have done the below.

Inside prepare()
{
.........
.........
 DataType.parseDateFromServer = this.parseDateAsMoment;
.........
.........
}

parseDateAsMoment(source: any): Date{

        var date = moment.utc(source, 'YYYY-MM-DD HH-mm-ss');        
        return date.toDate();
    }

--------------------------------------------------------------------------------------------
In Angular component, ondatechanged event of MyDatePicker.


 onDateFromChanged(event: IMyDateModel) {

        if (event.formatted !== '') {


            var newDate = moment.utc(new Date(event.jsdate).toLocaleDateString()).format('YYYY-MM-DD HH-mm-ss')
            var newDate2 = moment.utc(newDate, 'YYYY-MM-DD HH-mm-ss');
            this.model.dateFrom = newDate2.toDate();
        }


    }

Only then the date input stores correctly in SQL Server datetime column.
