### ISSUE TITLE
Incorrect references?? Files have been moved/refactored

### ISSUE THREAD

**Issue by nigel-dewar** [Breeze/temphire.angular#8]
Hi There,

Looking at this sample, just wondering if this is correct

In this file here temphire.angular/TempHire/app/resourcemgt/resource-mgt-unit-of-work.ts

there is
import { EntityManagerProvider, UnitOfWork, IRepository, EntityFactory, IEntityFactory } from '../core/services/common';

But looking in /core/services/  >> common has been removed, along with provide-parent, repository and unit-of-work etc

Is this right?

**Comment by marcelgood** [comment]
`/core/services/common.ts` hasn't been removed. It's still there.

https://github.com/Breeze/temphire.angular/blob/master/TempHire/app/core/services/common.ts

What has been removed is `/shared/services/common.ts` along with the entire `/shared/services` folder. All services have been moved to the core module. Based on the Angular Module Guide, a shared module shouldn't contain providers. This was just a clean up that I've been sitting on to be inline with the latest recommendations.

**Comment by nigel-dewar** [comment]
Ok Thank you, also looking at the files in core/services in this github repo I see,

unit-of-work.ts,
repository.ts,
provide-parent.ts,

But when I pull down a fresh repo to my local machine I do not see these files in core/services

I did a git pull and fetch, and a reset in attempt to get them, but to no avail

Am I missing something?

**Comment by nigel-dewar** [comment]
Ahhhhh, no worries. I hit the "show hidden files" in VS, and there they were! Sorry about that!

Thank you very much for this sample. Just one last thing. Does this sample demonstrate caching lookup entities in users local browser?  

Im referecing work done by John Papa's breeze angularjs 1.x course, and he makes good use of this technique, Im hoping your sample demonstrates how to cache entities locally and query them.

Cheers

**Comment by marcelgood** [comment]
Oh, looks like I forgot to update the csproj. I'll fix that. What do you mean my caching lookup entities in the user's browser. Yes, the lookup entities are cached for the duration of the session. They are fetched once and kept in a master manager and made available to every new EntityManager. They are not written to local storage and later retrieved for a future session if that's what you are looking for.

**Comment by nigel-dewar** [comment]
Yes thank you, that was what I was looking for, I can see now looking at your code that it does that.

Cheers, thanks very much, again, great sample.

One...... last question, I have read that it might be possible to use signalR on to notify the entitymanager to go fetch updates. Have you seen anyone doing this successfully?

**Comment by marcelgood** [comment]
I just pushed an updated csproj and cleaned up some deprecated code while I was at it. 

Regarding SignalR, yes we have done that before, but I don't have a sample that I can share. This is stuff we did for customer projects. You basically implement SignalR and send notifications to the clients when data changes on the server and then the clients decide if they need to go fetch the updated data. There is no particular consideration regarding Breeze for this kind of logic. This is custom logic in your app.

**Comment by nigel-dewar** [comment]
Thanks very much Marcel, appreciate that. I'll fetch latest changes.

Thanks for info on using SignalR, I thought that to be the case, as I could not see any harm notifying the client, and letting the client fetch updates. 

cheers

Nige.
