### ISSUE TITLE
Is rollup.js required?

### ISSUE THREAD

**Issue by nigel-dewar** [Breeze/temphire.angular#9]
Hi there,

I am attempting to implement breeze-client in angular-cli

Is the rollup.js required ?

In addition, in the enitity-manager-provider.ts,

How does one set the dataservice to point to a different api endpoint. ?

In this the code says, serviceName: 'breeze', this assumes the angular client just needs to communicate on the same localhost address/breeze right?
But I need it to go to something like http://localhost:56465/breeze

let dsconfig: DataServiceOptions = {
                serviceName: 'breeze'
            };
            if (location.port == '3000') {
                // Configure the json uriBuilder. See rollup.js comment above
                config.initializeAdapterInstance('uriBuilder', 'json', false);
                dsconfig.uriBuilderName = 'json'; // for breeze-sequelize server
            }

**Comment by marcelgood** [comment]
No, rollup is a different bundler. The angular-cli uses webpack. I'm planning on converting the sample to webpack eventually as it has become the bundler of choice for applications, whereas rollup is mostly used for libraries.

**Comment by nigel-dewar** [comment]
Ok thanks. So one MUST use rollup.js at this stage? As in, I cannot avoid requiring it, or... I cannot use it with webpack at all?  And should hang till a webpack implementation comes about.  I'm experimenting with angular2 breeze so I have not fortunately I can hang.

I found where serviceName is set using the no-db angular sample, so please ignore my previous query on this.

**Comment by marcelgood** [comment]
No, you don't have to use rollup.js. Application bundlers are an entirely different concern. All I'm saying is that the sample currently uses rollup.js. If you build your own app using the angular-cli you'll be using webpack to bundle the application. For real world applications we ourselves use webpack. The sample was first written at a time when it wasn't clear yet which one is gonna win. Webpack 2 is pretty much the winner as far as application bundlers are concerned at this point and it now fully supports AoT and tree shaking. At the time I wrote the sample, only rollup.js properly supported AoT and tree shaking.

**Comment by nigel-dewar** [comment]
Ok awesome that makes sense. A while back I was looking at angular2, and just ended up leaving it it till it matured in tooling etc.

Cheers.

**Comment by nigel-dewar** [comment]
Spent a few hours putting temphire angular code into a fresh angular-cli project.

Project loads up but then the error service gots nuts on a loop pumping out error messages something to do with modal which leads me to believe something to do with bootstrap.

Ill have to wait one day until you do an angular-cli build.

cheers for your help today however. Was really handy. 

Kind Regards

Nige
